travis:
  secure:
    BINSTAR_TOKEN: cNha6EIXrlOsJM/rapQJyqR+GXvIkccjKTLPmAzBmH+ffJaKiKyqPLdQif3/BRIfzv9042YF0YPrRVmYy3yDaHEuquMTvG0262ORo6tNgNNfETwJHBoz+XlPvvpd4vyXkSk3jlAQCAlYAIIHaG0weKkta857kxDm9UvD/8eVPJAXzRJGmvdBM6B98ArROW3p4qR869MoTjgN3d+/8n/Gnxf/8h9oCeilM7fF6/JTX6AQJU40Bz2sPljOMODUlawL6B6lPs5sNNsmiBltZCqoj5SuInxoyYkxaDXWISgM1P9jUnGdsA/iU+D7RrrI5S9BBN9xYfZfeo4qbNDwzOmYYG9c63F+Y72YNkek8DJqSnRHlt5mG8G6lJFoB0/rNJ3tDf2x9RS/d+8Igeh3ADG3gqUPP3LfwjQ5y1UAE7THxRTw6CqHNQ7WoCSRWihg9jdSOAn7auFJkm/xaUUYQvQLSKx3mmxl9ZfWw/yiNQDqwzUshLLQ+PNY7DeYRgyMo8BznsBxUuSZyR++RZwDBo09udgngfZP77jSdFqgakn7cDhkJAfZ8Mdib//0PIdTDoXf/DN3OewGBoe7H+TK/m9vZkFIVl4mOWy/G/HxvcSleEc0LhHwrP0MRTLblbhSpH/HdLxh349yHvRb/8/A/FPuphOepPskmPKRX33FnQoDqzo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
