travis:
  secure:
    BINSTAR_TOKEN: Ko23Ekuhgz1FfphYBGPDHLsp61hNEj4VA7mf/tbY1YZGRbbkDOTTl6Mq3IpL0Ffkk+t3zwRXlLDA2a3v6ftr2/ad7Jxe3nA57dhmXoLZr4W6bHqdv77dLuUOaiyM+T+l+QUtC4hdtBWTPPnMCXeEv0C/e386gflbW3Iy8v0GjZAYWAsBg36UZdhMUVbM3rNHH6TSadZVL/7N3Zp7lqApziLNaJiSaHP4Kyf6e47p+s+Bj9JImXDZFG+lzfa9+MHCeMdlmzkScYxVprbcU+kAyHrxoODtp8dOlb+X2pmmsvWkzRmwsz5aaaqByDPsLqi4sRgDtq6J/1NeRq7rWPYoVllDIU0XipEIOW1VdnN7wOA+okQO+E6EuvgZy6JGeKABfezQqy7OQ5HPT7/03Xs9hTBlk03J+gFN17UD2iUGZQhG1RxEXOuJuOI+w2YEMFtkZzlsK8h34DtheUlPdq+b+NDb8ke2KlXmFywTpDkBxHcE/W5V1DeU2Ehz1TzkV6f4wJdIoLgJVqQYJvxkfgwQEjCSqotHG2asKCKXiHURSp4ACs2yL84oo1kfkPpD+zhEB93IjED6J6cHx0LvrvhAa5r+9j8ibchNQcfjKsuoINg6hZ60Pai+xc+Vc4CeyjhPO11m3zHULTQunjO1vQOXSDj69r4KotBYDHqDuezgkZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
